# Generated by Django 4.1.2 on 2022-10-23 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_alter_photo_photo_alter_photo_tagged_pets'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LikePhoto',
            new_name='PhotoLike',
        ),
    ]
